//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NexusWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductShop
    {
        public int Id { get; set; }
        public int shopId { get; set; }
        public int productId { get; set; }
        public string pstatus { get; set; }
        public System.DateTime pregistrationdate { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
